# Site settings
title: Solace Messaging using Apache Qpid JMS 2.0 over AMQP
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-amqp-qpid-jms2"
repository: https://github.com/SolaceSamples/solace-samples-amqp-qpid-jms2

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Config Links
links-get-started-amqp: //dev.solace.com/get-started/amqp-tutorials/
links-get-started-amqp-jms1-dev: //dev.solace.com/get-started/amqp-tutorials-jms-11/
links-get-started-amqp-jms2-dev: //dev.solace.com/get-started/amqp-tutorials-jms-2/
links-get-started-amqp-jms1-cloud: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms1/
links-get-started-amqp-jms2-cloud: //cloud.solace.com/samples/solace-samples-amqp-qpid-jms2/
links-get-started-jms-dev: //dev.solace.com/get-started/jms-tutorials/
links-get-started-jms-cloud: //cloud.solace.com/samples/solace-samples-jms/
links-get-started-java-topic-to-queue-mapping: //dev.solace.com/get-started/java-tutorials/topic-queue-mapping_java/
links-get-started-jms-topic-to-queue-mapping: //dev.solace.com/get-started/jms-tutorials/topic-queue-mapping_jms/
links-community: //dev.solace.com/community/
links-downloads: //dev.solace.com/downloads/
links-tech-other: //dev.solace.com/tech/#other
links-jms1-specification: //download.oracle.com/otndocs/jcp/7195-jms-1.1-fr-spec-oth-JSpec/
links-jms2-specification: //download.oracle.com/otndocs/jcp/jms-2_0-fr-spec/
links-solaceCloud-setup: //cloud.solace.com/create-messaging-service/
docs-core-concepts: //docs.solace.com/Features/Core-Concepts.htm
docs-management-tools: //docs.solace.com/Management-Tools.htm
docs-management-soladmin: //docs.solace.com/SolAdmin/SolAdmin-Home.htm?Highlight=SolAdmin
docs-management-cli: //docs.solace.com/Configuring-and-Managing-Routers/Using-the-Solace-Router-CLI.htm
docs-topic-mapping: //docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-semp: //docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm
docs-semp-get-started: //docs.solace.com/SEMP/SEMP-Get-Started.htm
docs-confugure-queues: //docs.solace.com/Configuring-and-Managing-Routers/Configuring-Queues.htm
